{"start": 1556102536480, "befores": [{"status": "broken", "start": 1556102536480, "stop": 1556102536480, "name": "actions", "statusDetails": {"message": "TypeError: __init__() takes exactly 5 arguments (3 given)\n", "trace": "  File \"/Library/Python/2.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Python/2.7/site-packages/_pytest/fixtures.py\", line 969, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Python/2.7/site-packages/_pytest/fixtures.py\", line 828, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/mayank.mahajan/guavus-autothon/tests/test.py\", line 21, in actions\n    return Actions(base_url=self.proxy_server_base_url, test_header=self.test_header).generate_request()\n"}}], "stop": 1556102536728, "uuid": "3c0be076-5ee2-4b28-90ce-6f61c63365ff", "children": ["3d95e7d4-466c-490c-99c0-bd512e15af87"]}